namespace DocumentIA.Batch.Classification.Models;

public sealed record ClassificationExportRow(
    string FileName,
    string Status,
    string Typology,
    string TipologiaFamilia,
    string TipologiaVersion,
    string FechaProceso,
    string PaginasIncluidas,
    string Paginas,
    string Tdn1,
    string Tdn2,
    string Matricula,
    string Clasificador,
    string Confidence,
    string FallbackLLM,
    string DuracionTotalMs,
    string DetalleProveedoresReglasTipologia,
    string DetalleProveedoresReglasConfianza,
    string DetalleProveedoresReglasMotivoDescarte,
    string DetalleProveedoresDITipologia,
    string DetalleProveedoresDIConfianza,
    string DetalleProveedoresDIMotivoDescarte,
    string DetalleProveedoresFoundryRescueTipologia,
    string DetalleProveedoresFoundryRescueConfianza,
    string DetalleProveedoresFoundryRescueMotivoDescarte,
    string ReutilizadaPorDuplicado)
{
    public string[] ToValues() =>
    [
        FileName,
        Status,
        Typology,
        TipologiaFamilia,
        TipologiaVersion,
        FechaProceso,
        PaginasIncluidas,
        Paginas,
        Tdn1,
        Tdn2,
        Matricula,
        Clasificador,
        Confidence,
        FallbackLLM,
        DuracionTotalMs,
        DetalleProveedoresReglasTipologia,
        DetalleProveedoresReglasConfianza,
        DetalleProveedoresReglasMotivoDescarte,
        DetalleProveedoresDITipologia,
        DetalleProveedoresDIConfianza,
        DetalleProveedoresDIMotivoDescarte,
        DetalleProveedoresFoundryRescueTipologia,
        DetalleProveedoresFoundryRescueConfianza,
        DetalleProveedoresFoundryRescueMotivoDescarte,
        ReutilizadaPorDuplicado
    ];
}